config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users

    root to: "users#index"
  end

  resources :presences, only: %i[index]
  resources :schedules, only: %i[new create]

  get "login" => "sessions#new", as: :login
  post "login" => "sessions#create"
  post "logout" => "sessions#destroy", as: :logout

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.human_enum_name(enum_name, enum_value)
    enum_value = enum_value.to_s
    label = "activerecord.attributes.#{model_name.i18n_key}.#{enum_name.to_s.pluralize}.#{enum_value}"
    default = enum_value.titleize

    I18n.t(label, default: default)
  end
end

app/models/schedule.rb
class Schedule
  include ActiveModel::Model

  validates :start_date, :end_date, :status, presence: true
  validate :start_date_before_end_date

  attr_accessor :status
  attr_reader :start_date, :end_date

  def start_date=(start_date)
    return if start_date.blank?

    @start_date = Time.parse(start_date.to_s).utc
  end

  def end_date=(end_date)
    return if end_date.blank?

    @end_date = Time.parse(end_date.to_s).utc
  end

  private

  def start_date_before_end_date
    return unless start_date && end_date

    errors.add(:start_date, "should be before the end date") unless start_date < end_date
  end
end

app/models/user.rb
class User < ApplicationRecord
  include CableReady::Broadcaster
  before_validation :set_random_password

  authenticates_with_sorcery!

  enum role: { regular: "regular", admin: "admin" }
  enum status: { unavailable: "unavailable", available: "available", service: "service" }
  enum duty_type: {
    picket: "picket",
    elac: "elac",
    eip: "eip"
  }

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  default_scope { order(sort_index: :asc) }

  def next_status
    next_enum(User.statuses, status)
  end

  def next_duty_type
    next_enum(User.duty_types.merge(nil: nil), duty_type)
  end

  private

  def set_random_password
    return if admin? || password.present?

    self.password = SecureRandom.hex
    self.password_confirmation = password
  end

  def next_enum(enum, current_value)
    enum_index = current_value ? enum.keys.index(current_value) : -1
    is_last_index = enum_index == enum.keys.length - 1
    new_enum_index = is_last_index ? 0 : enum_index + 1
    new_enum_key = enum.keys[new_enum_index]

    enum[new_enum_key]
  end
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < Administrate::ApplicationController
    include HttpAcceptLanguage::AutoLocale

    before_action :authenticate_admin

    def authenticate_admin
      raise ActionController::RoutingError, "Not Found" unless current_user&.admin?
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    def create
      user = create_user

      if user.save
        redirect_to(
          [namespace, user],
          notice: translate_with_resource("create.success"),
        )
      else
        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, user)
        }
      end
    end

    private

    def create_user
      user = resource_class.new(resource_params)
      authorize_resource(user)

      unless user.password
        user.password = SecureRandom.hex
        user.password_confirmation = user.password
      end

      user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  before_action :require_login, :set_raven_context, :set_locale
  after_action :refresh_session
  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  private

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end

  def not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referer || root_path)
  end

  def set_raven_context
    Raven.user_context(username: current_user.username) if current_user
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end

  def set_locale
    I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
    session[:locale] = I18n.locale
  end

  def refresh_session
    ActiveRecord::SessionStore::Session.find_by(session_id: session.id&.private_id)&.touch # rubocop:disable all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/presences_controller.rb
class PresencesController < ApplicationController
  def index
    authorize :presences

    @users = User.all.order(:id)
    @available_users = @users.available.order(:id)
    @service_users = @users.service.order(:id)
    @picket_users = @users.picket.order(:id)
    @elac_users = @users.elac.order(:id)
    @eip_users = @users.eip.order(:id)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def new
    @schedule = Schedule.new
    @statuses = User.statuses.keys
  end

  def create
    @schedule = Schedule.new(schedule_params)
    @statuses = User.statuses.keys

    if @schedule.valid?
      schedule_status_change(@schedule)

      redirect_to(new_schedule_path, notice: "Scheduled!")
    else
      flash.now[:alert] = "Invalid!"

      render action: "new", status: :unprocessable_entity
    end
  end

  private

  def schedule_params
    params.require(:schedule).permit(:start_date, :end_date, :status)
  end

  def schedule_status_change(schedule)
    user_updater = UserUpdater.new(user: current_user)
    user_updater.delay(run_at: schedule.start_date.utc).toggle_status(schedule.status)
    user_updater.delay(run_at: schedule.end_date.utc).toggle_status(:unavailable)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    if current_user
      redirect_to(root_path)

      return
    end

    @user = User.new
  end

  def create
    @user = User.new(user_params)
    logged_in = login(user_params[:username], user_params[:password], true)

    if logged_in
      redirect_to(root_path, notice: "Login successful")
    else
      flash.now[:alert] = "Login failed"

      render action: "new", status: :unprocessable_entity
    end
  end

  def destroy
    logout

    redirect_to(login_path, notice: "Logged out!")
  end

  private

  def user_params
    @_user_params ||= params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(:id)
    @available_users = @users.available.order(:id)
    @service_users = @users.service.order(:id)
    @picket_users = @users.picket.order(:id)
    @elac_users = @users.elac.order(:id)
    @eip_users = @users.eip.order(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%= form_for([namespace, page.resource], html: { class: "form", autocomplete: "off" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t(
          "administrate.form.errors",
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")),
          resource_name: display_resource_name(page.resource_name).singularize
        ) %>
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% page.attributes.each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %> field-unit--<%= requireness(attribute) %>">
    <%= render_field attribute, f: f, autocomplete: "off" %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fields/enum_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.select field.attribute, field.select_field_values(f) %>
</div>

app/views/fields/enum_field/_index.html.erb
<%= field.to_s.titleize %>

app/views/fields/enum_field/_show.html.erb
<%= field.to_s.titleize %>

app/views/home/index.html.erb
<div class="Home-wrapper">
  <div class="Home-header">
    <h1><%= t("welcome") %> <%= current_user.username %></h1>
    <div class="Home-Logout">
      <% if current_user %>
        <%= button_to logout_path, { class: "Button" } do %>
          Logout
        <% end %>
      <% end %>
    </div>
  </div>
  <% if current_user.admin? %>
  <div class="Home-menu">
      <%= link_to t("presences"), presences_path, { class:"Home-link" } %>
      <%= link_to t("admin"), admin_users_path, { class: "Home-link", 'data-turbo': false } %>
  <% end %>
  <%= link_to t("schedules"), root_path, { class: "Home-link Home-link--disabled" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirefightersMonitor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="Application">
    <%= render(FlashMessageComponent.new(flash: flash)) %>

    <%= yield %>

    <%= javascript_include_tag "sentry", "data-turbo-track": "reload", async: true %>
  </body>
</html>

app/views/presences/index.html.erb
<div class="Presences">
  <div id="presences-list" class="Presences-list" data-controller="presences" data-presences-current_user_id=<%= current_user.id %>>
    <% @users.each do |user| %>
      <button
        id="presences-user-<%= user.id %>"
        class="Presences-user Presences-user--<%= user.status %>"
        data-user_id="<%= user.id %>"
        data-action="click->presences#toggleStatus contextmenu->presences#toggleDutyType"
      >
        <span class="Presences-user--block Presences-userName"><%= user.username %></span>

        <% if user.duty_type.present? %>
          <div class="Presences-userDutyType Presences-userDutyType--<%= user.duty_type %>">
            <%= User.human_enum_name(:duty_type, user.duty_type) %>
          </div>
        <% end %>

        <div class="Presences-user--block Presences-userStatus">
          <% unless user.unavailable? %>
            <%= User.human_enum_name(:status, user.status) %>
          <% end %>
        </div>
      </button>
    <% end %>
  </div>

  <div class="Presences-statuses">
    <div class="Presences-statuses--available">
      <h3><%= User.human_enum_name(:status, :available) %></h3>
      <% @available_users.each do |user| %>
        <span><%= user.username %></span>
      <% end %>
    </div>

    <div class="Presences-statuses--service">
      <h3><%= User.human_enum_name(:status, :service) %></h3>
      <% @service_users.each do |user| %>
        <span><%= user.username %></span>
      <% end %>
    </div>

    <div class="Presences-statuses--picket">
      <h3><%= User.human_enum_name(:duty_type, :picket) %></h3>
      <% @picket_users.each do |user| %>
        <span><%= user.username %></span>
      <% end %>
    </div>

    <% @elac_users.any? do %>
      <div class="Presences-statuses--elac">
        <h3><%= User.human_enum_name(:duty_type, :elac) %></h3>
        <% @elac_users.each do |user| %>
          <span><%= user.username %></span>
        <% end %>
      </div>
    <% end %>

    <% @eip_users.any? do %>
      <div class="Presences-statuses--eip">
        <h3><%= User.human_enum_name(:duty_type, :eip) %></h3>
        <% @eip_users.each do |user| %>
          <span><%= user.username %></span>
        <% end %>
      </div>
    <% end %>

    <%= link_to t("menu"), root_path, { class: "Presences-back" } %>
  </div>
</div>

app/views/schedules/new.html.erb
<%= form_with model: @schedule, method: :post do |f| %>
  <div>
    <%= f.label :start_date %>
    <%= f.text_field :start_date, class: "DatePicker-datetime" %>
    <%= render(FieldErrorsComponent.new(@schedule, :start_date)) %>
  </div>

  <div>
    <%= f.label :end_date %>
    <%= f.text_field :end_date, class: "DatePicker-datetime" %>
    <%= render(FieldErrorsComponent.new(@schedule, :end_date)) %>
  </div>

  <div>
    <%= f.label :status %>
    <%= f.select :status, @statuses %>
  </div>

  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="Users">
  <div class="Users-list" data-controller="users" data-users-current_user_id=<%= current_user.id %>>
    <% @users.each do |user| %>
      <button
        class="Users-user Users-user--<%= user.status %>"
        data-user_id="<%= user.id %>"
        data-action="click->users#toggleStatus contextmenu->users#toggleDutyType"
      >
        <span><%= user.username %></span>

        <% if user.duty_type.present? %>
          <div class="Users-userPicket">
            <%= t("users.#{user.duty_type}") %>
          </div>
        <% end %>

        <div class="Users-userStatus">
          <% unless user.unavailable? %>
            <%= t("users.#{user.status}") %>
          <% end %>
        </div>
      </button>
    <% end %>
  </div>

  <div class="Users-statuses">
    <h2><%= t("users.available") %></h2>

    <% @available_users.each do |user| %>
      <p><%= user.username %></p>
    <% end %>

    <h2><%= t("users.service") %></h2>

    <% @service_users.each do |user| %>
      <p><%= user.username %></p>
    <% end %>

    <h2><%= t("users.picket") %></h2>

    <% @picket_users.each do |user| %>
      <p><%= user.username %></p>
    <% end %>

    <h2><%= t("users.elac") %></h2>

    <% @elac_users.each do |user| %>
      <p><%= user.username %></p>
    <% end %>

    <h2><%= t("users.eip") %></h2>

    <% @eip_users.each do |user| %>
      <p><%= user.username %></p>
    <% end %>
  </div>
</div>